# Ruff configuration for the trading bot project

line-length = 100
indent-width = 4
src = ["src", "tests"]
extend-exclude = ["data/", "backup/"]

[lint]
select = [
  "E",  # pycodestyle errors
  "F",  # pyflakes
  "I",  # isort
  "B",  # flake8-bugbear
  "ARG",# unused arguments
  "C4", # comprehensions
  "SIM",# simplify
  "RET",# return
  "PL", # pylint common subset
  "RUF",# Ruff specific
]
ignore = [
  "E501",  # line length handled by formatter (Black)
]

[lint.per-file-ignores]
"tests/test_*_simple.py" = ["RUF001", "RUF002", "RUF003", "PLR2004"]
"tests/test_a32_*.py" = ["RUF001", "RUF002", "RUF003", "PLR2004", "F841", "F521"]
"src/ui/main_window.py" = ["RUF001", "RUF002", "RUF003"]
"tests/test_a32_microstructure.py" = ["PLR2004", "PLR0915", "ERA001"] # test constants and equality checks
"src/utils/microstructure.py" = ["PLR6301"] # global statement for singleton pattern

[lint.isort]
force-single-line = false
known-first-party = ["src"]
combine-as-imports = true

[format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
